[colors]
draw_bold_text_with_bright_colors = false

[cursor]
style = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 1

[[keyboard.bindings]]
chars = "\u001B[72;6u"
key = "H"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[74;6u"
key = "J"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[75;6u"
key = "K"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[76;6u"
key = "L"
mods = "Control|Shift"

[mouse]
hide_when_typing = false

# [mouse.double_click]
# threshold = 300

# [mouse.hints]
# launcher = "xdg-open"

# [mouse.triple_click]
# threshold = 300

[terminal.shell]
program = "/bin/zsh"
args = ["--login"]

[window]
decorations = "full"
dynamic_title = true
title = "Alacritty"
option_as_alt = 'Both'

[window.dimensions]
columns = 80
lines = 20

[window.padding]
x = 0
y = 0

[general]
import = ["~/.config/alacritty/themes/kanagawa-black.toml"]

[terminal]
